// ignore: constant_identifier_names
const Map<String, String> en_US = {
  'welcome': 'Welcome',
  'provide_email_title': 'Provide email',
  'provide_email_subtitle': "Provide your email address to verify,\nit's you.",
  'enter_your_email': 'Enter your email',
  'send_code': 'Send Code',
  'signup_welcome': 'Welcome!',
  'signup_subtitle': 'Register your account to\nstart precept study.',
  'email': 'Email',
  'enter_email_username': 'Enter your email or username',
  'username': 'Username',
  'enter_username': 'Enter your username',
  'confirm_password': 'Confirm Password',
  'do_you_have_account': 'Do you have an account? ',
  'welcome_back': 'Welcome Back!',
  'signin_subtitle': 'Log in to pick up where you left\noff in scripture.',
  'email_username': 'Email / Username',
  'password': 'Password',
  'enter_password': 'Enter your password',
  'email_or_username_empty': 'Email or username cannot be empty',
  'invalid_email_or_username':
      'Enter a valid email or username (min 3 characters)',
  'password_empty': 'Password cannot be empty',
  'password_min_length': 'Password must be at least 6 characters',
  'old_password': 'Old Password',
  'enter_old_password': 'Enter old password',
  'new_password': 'New Password',
  'at_least_6_characters': 'At least 6 characters',
  'password_not_match': 'Password not match',
  'form_fix_errors': 'Please fix the errors in the form',
  'error': 'Error',
  'success': 'Success',
  'email_empty': 'Email cannot be empty',
  'invalid_email': 'Enter a valid email',
  'username_empty': 'Username cannot be empty',
  'username_min_length': 'Username must be at least 3 characters',
  'confirm_password_empty': 'Confirm password cannot be empty',
  'passwords_do_not_match': 'Passwords do not match',
  'remember_me': 'Remember me',
  'forgot_password': 'Forgot Password?',
  'sign_in': 'Sign In',
  'dont_have_account': "Don't have an account? ",
  'sign_up': 'Sign Up',
  'settings': 'Settings',
  'language': 'Language',
  'select_language': 'Select Language',
  'dark_mode': 'Dark Mode',
  'light_mode': 'Light Mode',
  'get_started': 'Get Started',
  'precept_of_the_day': 'PRECEPT OF THE DAY',
  'create_topic': 'Create Topic',
  'app_title_line1': 'Precept',
  'app_title_line2': 'Study Bible',
  'menu_home': 'Home',
  'menu_bibles': 'Bibles',
  'menu_topics': 'Topics',
  'menu_profile': 'Profile',
  'invalid_date': 'Invalid date',
  'second': 'second',
  'minute': 'minute',
  'hour': 'hour',
  'day': 'day',
  'ago': 'ago',
  'add_topic': 'Add Topic',
  'from_selected_bible': 'From selected Bible content',
  'topic_name_label': 'Topic Name:',
  'topic_name_hint': 'Topic name',
  'add_precept': 'Add Precept',
  'precepts_label': 'Precept(s):',
  'precept_title_hint': 'Enter Precept (e.g. Genesis 1:1-5)',
  'precept_hint': 'Enter precept (e.g. Joshua 1-...)',
  'select_destination': 'Select Destination:',
  'precept_topic': 'Precept Topic',
  'favorite': 'Favorite',
  'please_select_destination': 'Please select a destination',
  'need_add_precept_first': 'You need to add a precept first',
  'please_enter_topic_name': 'Please enter a topic name',
  'save': 'Save',
  'topic_saved_success': 'Topic saved successfully!',
  'information_saved_successfully': 'Information saved successfully!',
  'search_hint': 'Search your topic',
  'ok': 'OK',
  'bible_search_label': 'Bible Search:',
  'option_all_words': 'All Words',
  'option_any_words': 'Any Words',
  'option_phrase': 'Phrase',
  'option_bible': 'Bible',
  'option_dan': 'Dan',
  'option_new_testament': 'New Testament',
  'option_old_testament': 'Old Testament',
  'bibles_title': 'Bibles',
  'search_bible': 'Search bible',
  'recommended_books': 'Recommended Books',
  'see_all': 'See All',
  'chapters_count': '{count} Chapters',
  'bible_title': 'Bible',
  'please_select_chapter': 'Please select a chapter',
  'select_chapter': 'Select Chapter',
  'chapter_label': 'Chapter {num}',
  'version_label': 'Version',
  'next': 'Next',
  'select_version': 'Select version',
  'chapter_title_format': '{title} {chapter}',
  'already_at_first_chapter': 'Already at first chapter',
  'already_at_last_chapter': 'Already at last chapter',
  'select_paragraphs_to_copy': 'Select paragraph(s) to copy',
  'copied_to_clipboard': 'Copied to clipboard',
  'select_paragraphs_to_share': 'Select paragraph(s) to share',
  'select_paragraphs_to_play': 'Select paragraph(s) to play',
  'select_paragraphs_to_repeat': 'Select paragraph(s) to repeat',
  'repeat_single_enabled': 'Repeat single enabled',
  'repeat_disabled': 'Repeat disabled',
  'select_paragraphs_to_add_to_topic': 'Select paragraph(s) to add to topic',
  'topic_dialog_closed': 'Topic dialog closed',
  'account_setting': 'Account Setting',
  'topics': 'Topics',
  'precept_topics': 'Precept Topics',
  'lesson_precepts': 'Lesson Precepts',
  'information_update': 'Information Update',
  'password_and_security': 'Password & Security',
  'favorites': 'Favorites',
  'information': 'Information',
  'click_to_update': 'Click to Update',
  'first_name': 'First Name',
  'last_name': 'Last Name',
  'email_address': 'Email Address',
  'bio': 'Bio',
  'downloads': 'Downloads',
  'locked': 'Locked',
  'unlocked': 'Unlocked',
  'share': 'Share',
  'download': 'Download',
  'topic_saved_offline': 'Topic saved for offline reading',
  'edit': 'Edit',
  'delete': 'Delete',
  'delete_topic': 'Delete Topic',
  'delete_topic_confirmation': 'Are you sure you want to delete',
  'delete_topic_cannot_undo': 'This action cannot be undone.',
  'cancel': 'Cancel',
  'deleting': 'Deleting',
  'installs_and_counting': 'Installs & Counting',
  'share_paragraph':
      "Because of you, God's word is\n reaching millions around the world.",
  'thank_you': 'Thank You!',
  'about': 'About',
  'help': 'Help',
  'log_out': 'Log out',
  'logout_confirm': 'Are you sure you\nwant to log out?',
  'precepts_tab': 'PRECEPTS',
  'lessons_tab': 'LESSONS',
  'favorites_tab': 'FAVORITES',
  'otp_verify': 'OTP Verify',
  'otp_subtitle':
      'We have sent you a 4 digit verification\ncode to your email. Please confirm and continue.',
  'resend': 'Resend',
  'verify': 'Verify',
  'otp_verified': 'OTP verified',
  'invalid_otp': 'Invalid OTP',
  'reset_password': 'Reset Password',
  'reset_password_subtitle': 'Set a new secure password for your account.',
  'please_wait': 'Please wait...',
  'invalid_request': 'Invalid request',
  'password_reset_success': 'Password reset successfully',
  'password_reset_failed': 'Password reset failed',
  'invalid_response': 'Invalid response from server',
  'unexpected_error': 'Unexpected error occurred',
};
