// ignore: constant_identifier_names
const Map<String, String> es_ES = {
  'welcome': 'Bienvenido',
  'provide_email_title': 'Proporcionar correo',
  'provide_email_subtitle':
      'Proporcione su dirección de correo electrónico para verificar,\nes usted.',
  'enter_your_email': 'Ingrese su correo electrónico',
  'send_code': 'Enviar código',
  'signup_welcome': '¡Bienvenido!',
  'signup_subtitle':
      'Registre su cuenta para\nempezar el estudio de preceptos.',
  'email': 'Correo electrónico',
  'enter_email_username': 'Ingrese su correo o nombre de usuario',
  'username': 'Nombre de usuario',
  'enter_username': 'Ingrese su nombre de usuario',
  'confirm_password': 'Confirmar contraseña',
  'sign_up': 'Regístrate',
  'do_you_have_account': '¿Tienes una cuenta? ',
  'welcome_back': '¡Bienvenido de nuevo!',
  'signin_subtitle':
      'Inicie sesión para continuar donde lo dejó\nen las escrituras.',
  'email_username': 'Correo / Nombre de usuario',
  'password': 'Contraseña',
  'enter_password': 'Ingrese su contraseña',
  'email_or_username_empty':
      'El correo electrónico o el nombre de usuario no puede estar vacío',
  'invalid_email_or_username':
      'Ingrese un correo electrónico o nombre de usuario válido (mínimo 3 caracteres)',
  'password_empty': 'La contraseña no puede estar vacía',
  'password_min_length': 'La contraseña debe tener al menos 6 caracteres',
  'old_password': 'Contraseña antigua',
  'enter_old_password': 'Ingrese la contraseña antigua',
  'new_password': 'Nueva contraseña',
  'at_least_6_characters': 'Al menos 6 caracteres',
  'password_not_match': 'La contraseña no coincide',
  'form_fix_errors': 'Por favor corrija los errores en el formulario',
  'error': 'Error',
  'success': 'Éxito',
  'email_empty': 'El correo electrónico no puede estar vacío',
  'invalid_email': 'Ingrese un correo electrónico válido',
  'username_empty': 'El nombre de usuario no puede estar vacío',
  'username_min_length':
      'El nombre de usuario debe tener al menos 3 caracteres',
  'confirm_password_empty':
      'La confirmación de la contraseña no puede estar vacía',
  'passwords_do_not_match': 'Las contraseñas no coinciden',
  'remember_me': 'Recuérdame',
  'forgot_password': '¿Olvidó su contraseña?',
  'sign_in': 'Iniciar sesión',
  'dont_have_account': '¿No tienes una cuenta? ',
  'settings': 'Ajustes',
  'language': 'Idioma',
  'select_language': 'Seleccionar idioma',
  'dark_mode': 'Modo oscuro',
  'light_mode': 'Modo claro',
  'get_started': 'Comenzar',
  'precept_of_the_day': 'PRECEPTO DEL DÍA',
  'create_topic': 'Crear tema',
  'app_title_line1': 'Precepto',
  'app_title_line2': 'Biblia de estudio',
  'menu_home': 'Inicio',
  'menu_bibles': 'Biblias',
  'menu_topics': 'Temas',
  'menu_profile': 'Perfil',
  'invalid_date': 'Fecha inválida',
  'second': 'segundo',
  'minute': 'minuto',
  'hour': 'hora',
  'day': 'día',
  'ago': 'hace',
  'add_topic': 'Agregar tema',
  'from_selected_bible': 'Desde el contenido de la Biblia seleccionado',
  'topic_name_label': 'Nombre del tema:',
  'topic_name_hint': 'Nombre del tema',
  'add_precept': 'Agregar precepto',
  'precepts_label': 'Precepto(s):',
  'precept_title_hint': 'Ingrese precepto (p. ej., Génesis 1:1-5)',
  'precept_hint': 'Ingrese el precepto (p. ej., Josué 1-...)',
  'select_destination': 'Seleccionar destino:',
  'precept_topic': 'Tema del precepto',
  'favorite': 'Favorito',
  'please_select_destination': 'Por favor seleccione un destino',
  'need_add_precept_first': 'Necesita agregar un precepto primero',
  'please_enter_topic_name': 'Por favor ingrese un nombre de tema',
  'save': 'Guardar',
  'topic_saved_success': '¡Tema guardado con éxito!',
  'information_saved_successfully': '¡Información guardada con éxito!',
  'search_hint': 'Buscar su tema',
  'ok': 'OK',
  'bible_search_label': 'Búsqueda bíblica:',
  'option_all_words': 'Todas las palabras',
  'option_any_words': 'Cualquier palabra',
  'option_phrase': 'Frase',
  'option_bible': 'Biblia',
  'option_dan': 'Dan',
  'option_new_testament': 'Nuevo Testamento',
  'option_old_testament': 'Antiguo Testamento',
  'bibles_title': 'Biblias',
  'search_bible': 'Buscar Biblia',
  'recommended_books': 'Libros recomendados',
  'see_all': 'Ver todo',
  'chapters_count': '{count} Capítulos',
  'bible_title': 'Biblia',
  'please_select_chapter': 'Por favor seleccione un capítulo',
  'select_chapter': 'Seleccionar capítulo',
  'chapter_label': 'Capítulo {num}',
  'version_label': 'Versión',
  'next': 'Siguiente',
  'select_version': 'Seleccionar versión',
  'chapter_title_format': '{title} {chapter}',
  'already_at_first_chapter': 'Ya en el primer capítulo',
  'already_at_last_chapter': 'Ya en el último capítulo',
  'select_paragraphs_to_copy': 'Seleccione párrafo(s) para copiar',
  'copied_to_clipboard': 'Copiado al portapapeles',
  'select_paragraphs_to_share': 'Seleccione párrafo(s) para compartir',
  'select_paragraphs_to_play': 'Seleccione párrafo(s) para reproducir',
  'select_paragraphs_to_repeat': 'Seleccione párrafo(s) para repetir',
  'repeat_single_enabled': 'Repetición de uno habilitada',
  'repeat_disabled': 'Repetición deshabilitada',
  'select_paragraphs_to_add_to_topic':
      'Seleccione párrafo(s) para agregar al tema',
  'topic_dialog_closed': 'Diálogo de tema cerrado',
  'account_setting': 'Configuración de la cuenta',
  'topics': 'Temas',
  'precept_topics': 'Temas de precepto',
  'lesson_precepts': 'Preceptos de la lección',
  'information_update': 'Actualización de información',
  'password_and_security': 'Contraseña y seguridad',
  'favorites': 'Favoritos',
  'information': 'Información',
  'click_to_update': 'Haga clic para actualizar',
  'first_name': 'Nombre',
  'last_name': 'Apellido',
  'email_address': 'Dirección de correo',
  'bio': 'Biografía',
  'downloads': 'Descargas',
  'locked': 'Bloqueado',
  'unlocked': 'Desbloqueado',
  'share': 'Compartir',
  'download': 'Descargar',
  'topic_saved_offline': 'Tema guardado para lectura sin conexión',
  'edit': 'Editar',
  'delete': 'Eliminar',
  'delete_topic': 'Eliminar tema',
  'delete_topic_confirmation': '¿Está seguro de que desea eliminar',
  'delete_topic_cannot_undo': 'Esta acción no se puede deshacer.',
  'cancel': 'Cancelar',
  'deleting': 'Eliminando',
  'installs_and_counting': 'Instalaciones y contando',
  'share_paragraph':
      'Gracias a ti, la palabra de Dios está\n llegando a millones en todo el mundo.',
  'thank_you': '¡Gracias!',
  'about': 'Acerca de',
  'help': 'Ayuda',
  'log_out': 'Cerrar sesión',
  'logout_confirm': '¿Estás seguro de que\nquieres cerrar sesión?',
  'precepts_tab': 'PRECEPTOS',
  'lessons_tab': 'LECCIONES',
  'favorites_tab': 'FAVORITOS',
  'otp_verify': 'Verificación OTP',
  'otp_subtitle':
      'Le hemos enviado un código de verificación de 4 dígitos a su correo electrónico. Por favor confirme y continúe.',
  'resend': 'Reenviar',
  'verify': 'Verificar',
  'otp_verified': 'OTP verificado',
  'invalid_otp': 'OTP inválido',
  'reset_password': 'Restablecer contraseña',
  'reset_password_subtitle':
      'Establezca una nueva contraseña segura para su cuenta.',
  'please_wait': 'Por favor espere...',
  'invalid_request': 'Solicitud inválida',
  'password_reset_success': 'Contraseña restablecida exitosamente',
  'password_reset_failed': 'Error al restablecer la contraseña',
  'invalid_response': 'Respuesta inválida del servidor',
  'unexpected_error': 'Ocurrió un error inesperado',
};
